language: c
compiler:
  - gcc
# - clang
env:
  global:
    - "BUILD_DIR=$TRAVIS_BUILD_DIR"
    - "LD_LIBRARY_PATH=\"$BUILD_DIR/target:$LD_LIBRARY_PATH\""
    - secure: "TJU+3+AOUuxTzDrD0UJKDecAyR+0PYvjJhS5x3QtmH/Aj3LBz19DiCT8/cKifgxRfC+9FaHBqSUT72oTGvZ9HL+zcN383kyzSzsF2yJTIx8RM+t5qlp/ioL6juO0fh5vHpYeCybjUsvWJfHPQ7uLD7ngWY0qCjShcAGuqVGIbA0="
    - secure: "Pn/KA8W8hOdWY0ghA7xAB+yundO/avjBFtZ9jq3zONM6LDOOaKu+UbqtEh+qlfp7sUTOPVhAI1H9XOangVgTCb/jU4y7eTp21xrJrKt87i4XJv3YVnO9eDmjCEY3XP36/O6dRjcEbKJOLHiJZRY3zA36a9zxUOn22Y93gbwDMtU="
before_install:
  - echo 'deb http://apt.cadrian.net/ unstable main' | sudo tee /etc/apt/sources.list.d/cadrian.list
  - "sudo apt-get update -q"
  - "sudo apt-get install -q --force-yes libcad0 libcad-dev libpcre3 libpcre3-dev rsync graphviz doxygen doxygen-latex texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra fonts-linuxlibertine fonts-inconsolata devscripts"
  - openssl aes-256-cbc -K $encrypted_9d180897fb79_key -iv $encrypted_9d180897fb79_iv -in utils/sshkey.tgz.enc -out utils/sshkey.tgz -d
  - "tar xfz utils/sshkey.tgz -C $HOME && chmod 700 $HOME/.ssh"
install:
  - "make exe"
script:
  - "test/test.sh all"
after_success:
  - "make clean; build/build.sh main; sudo dpkg -i target/dpkg/*.deb"
  - "rsync -aSH --stats -e 'ssh -i '$HOME'/.ssh/id_rsa_exp -p '$PORT' -q -C -o StrictHostKeyChecking=no' target/dpkg/*.deb target/dpkg/*.dsc target/dpkg/*.tar.gz $HOST:apt/incoming/"
  - "rsync -aSH --stats -e 'ssh -i '$HOME'/.ssh/id_rsa_exp -p '$PORT' -q -C -o StrictHostKeyChecking=no' target/dpkg/*.changes $HOST:apt/incoming/"
